# Model arguments
model_name_or_path: mistralai/Mistral-7B-Instruct-v0.3
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# LoRA arguments
load_in_4bit: true
use_peft: true
lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj

# Data training arguments
dataset_mixer:
  GaetanMichelet/chat-60_ft_task-2_auto: 1.0
  GaetanMichelet/chat-120_ft_task-2_auto: 1.0
  GaetanMichelet/chat-180_ft_task-2_auto: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# SFT trainer config
bf16: true
do_eval: true
eval_strategy: epoch
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Mistral-7B_task-2_180-samples_config-1_auto
hub_strategy: every_save
learning_rate: 1.0e-04
log_level: info
logging_steps: 2
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 8192
max_steps: -1
num_train_epochs: 50
output_dir: data/Mistral-7B_task-2_180-samples_config-1_auto
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
push_to_hub: true
report_to:
- tensorboard
save_strategy: epoch
save_steps: 25
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
load_best_model_at_end: true
